# Site settings
title: Short End - URL Shortener
author: John Goodliff
description: 'An experimental client-side URL shortener'
# Used by Jekyll
url: 'l.johng.io'
github_url: 'https://github.com/jerboa88/short-end'
privacy_policy_url: 'https://johng.io/privacy-policy'

# Build settings
markdown: kramdown
permalink: pretty

# Collection definitions and settings
collections:
  links:
    output: true
    permalink: /:path/

# Set default layout for link pages
defaults:
  - scope:
      path: '' # An empty string here means all files in the project
      type: links
    values:
      layout: link_page
